# Generated by Django 6.0.5 on 2026-05-12 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=9)),
                ('period_number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Учебный период',
                'verbose_name_plural': 'Учебный период',
                'ordering': ['period_name', 'academic_year'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('hours_per_year', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('учитель', 'Учитель'), ('студент', 'Студент'), ('админ', 'Админ')], default='student', max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('мама', 'Мама'), ('папа', 'Папа'), ('опекун', 'Опекун'), ('Другое', 'Другое')], max_length=20)),
                ('child_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='journal.person')),
                ('parent_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='journal.person')),
            ],
            options={
                'verbose_name': 'Родители',
                'verbose_name_plural': 'Родители',
                'ordering': ['parent_person', 'child_person'],
            },
        ),
        migrations.CreateModel(
            name='GradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('lesson_number', models.PositiveSmallIntegerField()),
                ('topic', models.TextField(blank=True, null=True)),
                ('homework', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='journal.person')),
            ],
            options={
                'verbose_name': 'Журнал успеваемости',
                'verbose_name_plural': 'Журналы успеваемости',
                'ordering': ['school_class', 'subject', 'teacher', 'lesson_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_value', models.CharField(max_length=10)),
                ('grade_type', models.CharField(choices=[('lesson', 'Lesson'), ('homework', 'Homework'), ('control', 'Control'), ('project', 'Project'), ('oral', 'Oral')], default='lesson', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='journal.gradebook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='journal.person')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['student', 'grade_value'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_note', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='journal.gradebook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='journal.person')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемости',
                'ordering': ['student', 'attendance_status'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, unique=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('archived', 'Archived')], default='active', max_length=20)),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_classes', to='journal.person')),
            ],
            options={
                'verbose_name': 'Школьный класс',
                'verbose_name_plural': 'Школьные классы',
                'ordering': ['class_name'],
            },
        ),
        migrations.AddField(
            model_name='gradebook',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='journal.schoolclass'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('departure_order', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('departure_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='journal.person')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='journal.schoolclass')),
            ],
            options={
                'verbose_name': 'Зачисление',
                'verbose_name_plural': 'Зачисления',
                'ordering': ['departure_order', 'departure_date'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('lesson_number', models.PositiveSmallIntegerField()),
                ('room', models.CharField(blank=True, max_length=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_schedules', to='journal.person')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='journal.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='journal.subject')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['school_class', 'subject', 'teacher', 'day_of_week'],
            },
        ),
        migrations.AddField(
            model_name='gradebook',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='journal.subject'),
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_grade', models.CharField(max_length=10)),
                ('calculated_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('is_exam', models.BooleanField(default=False)),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='journal.person')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='journal.schoolperiod')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='journal.subject')),
            ],
            options={
                'verbose_name': 'Итоговая оценка',
                'verbose_name_plural': 'Итоговые оценки',
                'ordering': ['student', 'final_grade'],
            },
        ),
    ]
