# Generated by Django 6.0.5 on 2026-05-06 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=9)),
                ('period_number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('hours_per_year', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('child_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='pages.person')),
                ('parent_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='GradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('lesson_number', models.PositiveSmallIntegerField()),
                ('topic', models.TextField(blank=True, null=True)),
                ('homework', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_value', models.CharField(max_length=10)),
                ('grade_type', models.CharField(choices=[('lesson', 'Lesson'), ('homework', 'Homework'), ('control', 'Control'), ('project', 'Project'), ('oral', 'Oral')], default='lesson', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='pages.gradebook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_note', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='pages.gradebook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, unique=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('archived', 'Archived')], default='active', max_length=20)),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_classes', to='pages.person')),
            ],
        ),
        migrations.AddField(
            model_name='gradebook',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='pages.schoolclass'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('departure_order', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('departure_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='pages.person')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='pages.schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('lesson_number', models.PositiveSmallIntegerField()),
                ('room', models.CharField(blank=True, max_length=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_schedules', to='pages.person')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pages.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pages.subject')),
            ],
        ),
        migrations.AddField(
            model_name='gradebook',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='pages.subject'),
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_grade', models.CharField(max_length=10)),
                ('calculated_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('is_exam', models.BooleanField(default=False)),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='pages.person')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='pages.schoolperiod')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='pages.subject')),
            ],
        ),
    ]
