# Generated by Django 6.0.5 on 2026-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('учитель', 'Учитель'), ('студент', 'Студент'), ('админ', 'Админ')], default='студент', max_length=20),
        ),
    ]
